#!/bin/sh

GCA="\033[1mGit Audio\033[0m"
CONFIG="$HOME/.git-audio/config.sh"

if [ ! -f $CONFIG ]; then
  printf "$GCA: configuration not found, please re-install.\n\n"
  exit 1
fi

. $CONFIG

if [ ! -f $GIT_AUDIO ]; then
  printf "$GCA: audio not found $GIT_AUDIO\n\n"
  exit 1
fi

OS=$(uname)
case $OS in
  Darwin)
    afplay $GIT_AUDIO &
    ;;
  Linux)
    if command -v aplay >/dev/null 2>&1; then
      aplay -q $GIT_AUDIO &
    elif command -v paplay >/dev/null 2>&1; then
      paplay $GIT_AUDIO &
    else
      printf "$GCA: audio player not found.\n\n"
    fi
    ;;
  *)
    printf "$GCA: unsupported OS $OS\n\n"
esac
