#!/bin/sh

GCA="\033[1mGit Audio\033[0m"
CONFIG="$HOME/.git-audio/config.sh"

if [ ! -f $CONFIG ]; then
  echo "\n$GCA: configuration not found, please re-install.\n"
  exit 1
fi

source $CONFIG

if [ ! -f $GIT_COMMIT_AUDIO ]; then
  echo "\n$GCA: audio not found $GIT_COMMIT_AUDIO\n"
  exit 1
fi

OS=$(uname)
case $OS in
  Darwin)
    afplay $GIT_COMMIT_AUDIO &
    ;;
  Linux)
    if command -v aplay >/dev/null 2>&1; then
      aplay $GIT_COMMIT_AUDIO &
    elif command -v paplay >/dev/null 2>&1; then
      paplay $GIT_COMMIT_AUDIO &
    else
      echo "\n$GCA: audio player not found.\n"
    fi
    ;;
  *)
    echo "\n$GCA: unsupported OS $OS\n"
esac
