#!/bin/sh

if [ ! -f "$GIT_COMMIT_AUDIO" ]; then
  echo "Git Commit Audio: audio not found '$GIT_COMMIT_AUDIO'"
  exit 1
fi

OS="$(uname)"
case "$OS" in
  Darwin)
    afplay "$GIT_COMMIT_AUDIO" &
    ;;
  Linux)
    if command -v aplay >/dev/null 2>&1; then
      aplay "$GIT_COMMIT_AUDIO" &
    elif command -v paplay >/dev/null 2>&1; then
      paplay "$GIT_COMMIT_AUDIO" &
    else
      echo "Git Commit Audio: audio player not found."
      exit 1
    fi
    ;;
  *)
    echo "Git Commit Audio: unsupported OS $OS"
    exit 1
esac
